- Platform:
    - Homepage:
        href: http://home.home
        description: Dashboard
        icon: homepage
        server: my-docker
        container: homepage
    - Dockge:
        href: http://dockge.home
        description: Stack Management
        icon: dockge
        server: my-docker
        container: dockge
    - Uptime Kuma:
        href: http://status.home
        description: Health Monitoring
        icon: uptime-kuma
        server: my-docker
        container: uptime-kuma
    - Caddy:
        description: Reverse Proxy
        icon: caddy
        server: my-docker
        container: caddy
    - Authentik:
        href: http://login.home
        description: Identity & SSO
        icon: authentik
        server: my-docker
        container: authentik-server
    - Backrest:
        href: http://backup.home
        description: Backup Management
        icon: mdi-backup-restore
        server: my-docker
        container: backrest

- Applications:
    - Immich:
        href: http://immich.home
        description: Photos & Videos
        icon: immich
        server: my-docker
        container: immich-server
    - Copyparty:
        href: http://copyparty.home
        description: File Sharing
        icon: mdi-folder-multiple
        server: my-docker
        container: copyparty
    - Jellyfin:
        href: http://jellyfin.home
        description: Media Streaming
        icon: jellyfin
        server: my-docker
        container: jellyfin
